
all:
	cc -Wall -o lnf_example1 -I ../include -lnf -L ../src/.libs lnf_example1.c
	cc -o lnf_example2 -I ../include -lnf -L ../src/.libs lnf_example2.c

clean:
	rm -f testfile lnf_example1 lnf_example2


